CREATE TABLE `train` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `train_num` varchar(32) NOT NULL COMMENT '车次号',
  `train_type` tinyint(4) NOT NULL COMMENT '车次类型：type：0:高铁,1:城际,2:动车,3:直达,4:特快,5:普快,6:其他',
  `train_type_name` varchar(16) NOT NULL COMMENT '车次类型名称',
  `depart_city_name` varchar(16) NOT NULL COMMENT '出发城市名称',
  `depart_city_code` varchar(8) NOT NULL COMMENT '出发城市三字码',
  `dest_city_name` varchar(16) NOT NULL COMMENT '到达城市名称',
  `dest_city_code` varchar(8) NOT NULL COMMENT '到达城市三字码',
  `depart_station_name` varchar(16) NOT NULL COMMENT '始发站名称',
  `depart_station_code` varchar(8) NOT NULL COMMENT '始发站三字码',
  `dest_station_name` varchar(16) NOT NULL COMMENT '到达站名称',
  `dest_station_code` varchar(8) NOT NULL COMMENT '到达站三字码',
  `depart_time` varchar(5) NOT NULL COMMENT '始发时间',
  `arrive_time` varchar(5) NOT NULL COMMENT '到站时间',
  `duration` int(11) NOT NULL COMMENT '历时：单位分钟',
  `duration_day` tinyint(4) NOT NULL,
  `distance` decimal(10,2) NOT NULL COMMENT '里程（公里）',
  `seats` varchar(25) NOT NULL COMMENT '坐等：0：商务座,1：特等座,2：一等座,3：二等座,4：高级软卧,5：软卧,6：硬卧,7：软座,8：硬座,9：无座',
  `inteval` tinyint(2) NOT NULL COMMENT '发车间隔：0：状态未知；1：每天都发车；2：隔天发车；其他类推',
  `op_time` datetime NOT NULL COMMENT '操作实际',
  `del_flag` tinyint(4) NOT NULL COMMENT '删除标识:0未删除,1已删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`),
  UNIQUE KEY `train_num_UNIQUE` (`train_num`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;