CREATE TABLE `train_station` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `station_code` varchar(8) NOT NULL COMMENT '车站ID',
  `station_num` tinyint(4) NOT NULL COMMENT '站序：1：第一站；2：第二站；其他类推',
  `station_name` varchar(8) NOT NULL COMMENT '车站名称',
  `train_id` int(10) NOT NULL COMMENT '车次ID',
  `train_num` varchar(32) NOT NULL COMMENT '车次号',
  `train_type` tinyint(4) NOT NULL COMMENT '车次类型：type：0:高铁,1:城际,2:动车,3:直达,4:特快,5:普快,6:其他',
  `city_code` varchar(8) NOT NULL COMMENT '城市ID',
  `city_name` varchar(8) DEFAULT NULL COMMENT '城市',
  `depart_time` varchar(8) NOT NULL COMMENT '发车时间',
  `arrive_time` varchar(8) NOT NULL COMMENT '到达时间',
  `stay_time` int(11) NOT NULL DEFAULT '0' COMMENT '停留时间',
  `duration_day` tinyint(4) NOT NULL DEFAULT '1' COMMENT '经过天数：1：当天到达；2：隔天到达；其他类推',
  `distance` decimal(10,2) DEFAULT NULL COMMENT '里程',
  `type` tinyint(4) NOT NULL COMMENT '过路类型：0:始发；1:过路；2:终点',
  `seats` varchar(25) DEFAULT NULL COMMENT '坐等：0：商务座,1：特等座,2：一等座,3：二等座,4：高级软卧,5：软卧,6：硬卧,7：软座,8：硬座,9：无座',
  `op_time` datetime NOT NULL COMMENT '操作时间',
  `op_uid` int(10) DEFAULT '0' COMMENT '更新人id',
  `op_name` varchar(10) DEFAULT '' COMMENT '更新人',
  `del_flag` tinyint(4) DEFAULT '0' COMMENT '删除标识:0未删除,1已删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_train_station` (`train_id`,`station_code`)
) ENGINE=InnoDB AUTO_INCREMENT=176737 DEFAULT CHARSET=utf8;